use egui::epaint::text::{FontInsert, InsertFontFamily};
use font_kit::{family_name::FamilyName, properties::Properties, source::SystemSource};
use std::fs::File;
use std::io;

const FONT_CANDIDATES: [&str; 14] = [
    // Hoping for this to be present
    "Noto Sans JP",
    // Otherwise try some common fallback fonts
    // List generated by an LLM since I have no clue. If this can be improved, I'm open to it
    "IPAexGothic",
    "IPAGothic",
    "TakaoPGothic",
    "Takao Gothic",
    "VL Gothic",
    "Yu Gothic UI",
    "Yu Gothic",
    "Meiryo",
    "MS PGothic",
    "MS Gothic",
    "Hiragino Sans",
    "Hiragino Kaku Gothic ProN",
    "Hiragino Kaku Gothic Pro",
];
const FONT_URL: &str =
    "https://github.com/googlefonts/noto-cjk/raw/main/Sans/Variable/OTC/NotoSansCJK-VF.otf.ttc";

pub fn load_main_font(ctx: &egui::Context, font: &str) {
    tracing::info!("Trying to load a supported font.");

    let font_data: Option<Vec<u8>> = check_system_for_default(font)
        .or_else(|| check_system_fonts())
        .or_else(|| check_cached_font())
        .or_else(|| fetch_font());

    if let Some(data) = font_data {
        tracing::info!("Successfully loaded a supported font.");

        ctx.add_font(FontInsert::new(
            "default font",
            egui::FontData::from_owned(data),
            vec![
                InsertFontFamily {
                    family: egui::FontFamily::Proportional,
                    priority: egui::epaint::text::FontPriority::Highest,
                },
                InsertFontFamily {
                    family: egui::FontFamily::Monospace,
                    priority: egui::epaint::text::FontPriority::Lowest,
                },
            ],
        ));
    } else {
        tracing::warn!(
            "Failed to load a supported font. Make sure you have an active internet connection or try manually installing the Noto Sans (CJK) JP font to your system."
        );
    }
}

fn check_system_for_default(font: &str) -> Option<Vec<u8>> {
    tracing::debug!("Checking system for default font.");

    let result = SystemSource::new()
        .select_best_match(&[FamilyName::Title(font.to_string())], &Properties::new())
        .ok()
        .and_then(|handle| handle.load().ok())
        .and_then(|font| {
            tracing::debug!("Found default font in system: {}", font.family_name());
            font.copy_font_data()
        })
        .map(|data| data.to_vec());

    if let Some(data) = result {
        return Some(data);
    }

    None
}

fn check_system_fonts() -> Option<Vec<u8>> {
    tracing::debug!("Checking for supported system fonts.");

    for family in FONT_CANDIDATES {
        let result = SystemSource::new()
            .select_best_match(&[FamilyName::Title(family.to_string())], &Properties::new())
            .ok()
            .and_then(|handle| handle.load().ok())
            .and_then(|font| {
                tracing::debug!("Found system font candidate: {}", font.family_name());
                font.copy_font_data()
            })
            .map(|data| data.to_vec());

        if let Some(data) = result {
            return Some(data);
        }
    }
    None
}

fn check_cached_font() -> Option<Vec<u8>> {
    tracing::debug!("Checking for downloaded default font.");

    if let Some(mut data_dir_path) = dirs::data_dir() {
        let font_path = data_dir_path.join("popup_dictionary").join("font.otf");
        std::fs::read(font_path).ok()
    } else {
        tracing::warn!(
            "Could not load cached font: No valid data path found in environment variables."
        );
        None
    }
}

fn fetch_font() -> Option<Vec<u8>> {
    tracing::debug!("Fetching default font.");

    let data = reqwest::blocking::get(FONT_URL)
        .ok()?
        .error_for_status()
        .ok()?
        .bytes()
        .ok()?
        .to_vec();

    if let Some(mut data_dir_path) = dirs::data_dir() {
        let font_path = data_dir_path.join("popup_dictionary").join("font.otf");

        if let Some(parent) = font_path.parent() {
            std::fs::create_dir_all(parent).ok()?;
        }
        std::fs::write(&font_path, &data).ok()?;

        Some(data)
    } else {
        tracing::warn!(
            "Could not load cached font: No valid data path found in environment variables."
        );
        None
    }
}
